"""Render docs/capabilities.md from the executable cells in snn_opt.capabilities.

Usage: ``python tools/render_capabilities.py`` from the repository root (with
the compiled kernel built, including OpenMP). Every software cell is executed;
the script exits non-zero, without writing, when any cell's behaviour differs
from the classification its row declares, or when the build cannot run every
backend. The output is deterministic: no timestamps and no timings.
"""

import re
import sys
from collections import Counter
from pathlib import Path

from snn_opt import capabilities as cap

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "capabilities.md"
ENV_KEYS = ("kernel", "maximum_n", "maximum_m", "full_square_cap", "cg_square_cap",
            "stream_dimension_cap")
HEADER = ("<!-- GENERATED by tools/render_capabilities.py from src/snn_opt/capabilities.py;"
          " do not edit. -->")


def _env_value(package, key):
    path = ROOT / package / "env.yaml"
    text = path.read_text() if path.exists() else ""
    match = re.search(rf"^{key}:\s*([^\s#]+)", text, re.MULTILINE)
    return match.group(1) if match else "-"


def current_packages():
    """``package:`` values named by fpga/CURRENT, or () when it is absent."""
    path = ROOT / "fpga" / "CURRENT"
    if not path.exists():
        return ()
    return tuple(sorted(set(re.findall(r"^\s*package:\s*(\S+)", path.read_text(), re.MULTILINE))))


def _software(mismatches):
    head = ["Set type"] + [f"{s} `{b}`" for s, b in cap.COLUMNS]
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    messages, counts = {}, {col: Counter() for col in cap.COLUMNS}
    for row in cap.ROWS:
        cells = []
        for j, col in enumerate(cap.COLUMNS):
            out = cap.probe(row, j)
            if out.status != row.expected(j):
                mismatches.append(f"{row.set_type} / {col}: expected {row.expected(j)}, "
                                  f"observed {out.status} {out.detail}")
            counts[col][out.status] += 1
            if out.status == "raises":
                key = messages.setdefault(out.detail, f"r{len(messages) + 1}")
                cells.append(f"raises [{key}]")
            elif out.status == "fallback":
                cells.append(f"fallback: {out.detail}")
            else:
                cells.append({"n/a": "-"}.get(out.status, out.status))
        lines.append(f"| {row.set_type} | " + " | ".join(cells) + " |")
    summary = ["| Column | native | fallback | raises |", "|---|---|---|---|"]
    for col in cap.COLUMNS:
        c = counts[col]
        summary.append(f"| {col[0]} `{col[1]}` | {c['native']} | {c['fallback']} | {c['raises']} |")
    raises = [f"- **{key}**: `{msg}`" for msg, key in messages.items()]
    return lines, summary, raises


def _fpga():
    packages = sorted(cap.FPGA_BOUNDARIES)
    current = current_packages()
    head = ["Feature"] + [f"`{p}`" for p in packages]
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    for feature in cap.FPGA_FEATURES:
        lines.append(f"| {feature} | " + " | ".join(
            cap.FPGA_BOUNDARIES[p][feature] for p in packages) + " |")
    for key in ENV_KEYS:
        lines.append(f"| `env.yaml` {key} | " + " | ".join(
            _env_value(p, key) for p in packages) + " |")
    if current:
        lines.append("| current (`fpga/CURRENT`) | " + " | ".join(
            "yes" if p in current else "no" for p in packages) + " |")
    evidence = [f"- `{p}`: " + ", ".join(f"`{e}`" for e in cap.FPGA_BOUNDARIES[p]["evidence"])
                for p in packages]
    note = ("`fpga/CURRENT` names: " + ", ".join(f"`{p}`" for p in current) + "."
            if current else "`fpga/CURRENT` is not present in this tree.")
    return lines, evidence, note


def render():
    """Return (markdown, mismatches)."""
    mismatches = []
    table, summary, raises = _software(mismatches)
    fpga, evidence, current_note = _fpga()
    text = "\n".join([
        HEADER, "",
        "# Capability matrix", "",
        "Which set types run where. Every software cell below is a small strictly convex",
        "problem that `tools/render_capabilities.py` solves through the public API; the",
        "cell records what happened, and `tests/test_capabilities.py` fails if that",
        "differs from the expectation declared in `src/snn_opt/capabilities.py` or if",
        "this page is stale. Rerun the tool after changing any capability.", "",
        "- **native**: solves without rewriting the set; on a compiled backend the result",
        f"  also matches `backend='python'` to {cap.PARITY_ATOL:g}; a Dykstra cell must",
        "  also reproduce the Python per-step inner iteration and projection event counts",
        "  exactly, and a cell whose Python reference raises is an error, not native.",
        "- **fallback**: solves through a rewrite the code performs (named in the cell).",
        "- **raises**: fails closed at construction or solve with the message listed below.",
        "- **-**: not applicable, or not probed for this row.", "",
        "Columns: `greedy` is the default event sweep (`projection_method='adaptive'`);",
        "`dykstra` puts the set's rows and candidates (and a box, as an `np.clip`",
        "callable) inside one `joint_dykstra_projector`; `eigenbasis` is",
        "`transform='eigenbasis'`; `ivp` is `integration_method='ivp'`; `fixed` is",
        "`projection_method='fixed'`. `backend='c'` resolves to `c_openmp` when the",
        "build has OpenMP and to `c_serial` otherwise, with identical results.", "",
        "## Software backends", "", *table, "",
        "### Counts per column", "", *summary, "",
        "### Raise messages", "", *raises, "",
        "## FPGA packages (declared boundaries)", "",
        "FPGA packages are not executed here. Their boundaries are declared once in",
        "`snn_opt.capabilities.FPGA_BOUNDARIES` from each package's own documentation;",
        "limits are read from each package's `env.yaml`. Values: **native** (in the",
        "kernel), **software** (the package states it stays host-side), **not_qualified**",
        "(present or unstated, but not board-qualified), **absent** (not provided).", "",
        *fpga, "",
        current_note,
        "No eigenbasis FPGA package exists in this repository.", "",
        "Evidence cited per package:", "", *evidence, "",
    ])
    return text, mismatches


def main():
    missing = [b for b in sorted({b for _, b in cap.COLUMNS}) if not cap.backend_available(b)]
    if missing:
        print(f"cannot render: this build cannot run {missing}", file=sys.stderr)
        return 2
    text, mismatches = render()
    if mismatches:
        print("capability expectations do not match behaviour:", file=sys.stderr)
        print("\n".join(mismatches), file=sys.stderr)
        return 1
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
